name: CI

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  sdcc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download SDCC
      run: |
        wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        tar -xf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        echo `pwd`/sdcc-4.0.0/bin >> $GITHUB_PATH
        sudo apt install -y build-essential

    - name: Build examples
      run: make
      working-directory: examples

  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install SDCC
      run: sudo apt-get install -y sdcc

    - name: Build examples
      run: make
      working-directory: examples
